ALTER TABLE `line`
ADD COLUMN `expand` TINYINT NOT NULL DEFAULT 0
AFTER `idc_id`;
ALTER TABLE `pool`
ADD COLUMN `expand` TINYINT NOT NULL DEFAULT 0
AFTER `ipaddrs`;
ALTER TABLE `idc`
ADD COLUMN `expand` TINYINT NOT NULL DEFAULT '0'
AFTER `enabled`;